language: node_js
dist: trusty

cache:
  directories:
    - node_modules

env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

matrix:
  fast_finish: true
  include:
    - node_js: "6"
      os: linux
      env: SCRIPT=lint
    - node_js: "6"
      os: linux
      env: SCRIPT=test:unit
    - node_js: "6"
      os: linux
      env: NODE_SCRIPT=tests/run_e2e.js
    - node_js: "8"
      os: linux
      env: NODE_SCRIPT=tests/run_e2e.js
    - node_js: "8"
      os: linux
      env: SCRIPT=protractor:ci

before_install:
  - npm config set spin false
  - npm config set progress false
  - npm install npm@5 -g
  - npm cache clean --force

install:
  - npm install

after_install:
  - ./node_modules/protractor/bin/webdriver-manager update

before_script:
  - export DISPLAY=:99
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi
  - if [[ "$NODE_SCRIPT" ]]; then node $NODE_SCRIPT; fi
